try to ignore the qemu-user-static setup / nftables

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -43,7 +43,7 @@ variables:
 before_script:
   - >
     dnf install -y --nodocs --setopt=install_weak_deps=False
-    buildah podman skopeo runc crun qemu-user-binfmt jq curl fuse-overlayfs nftables
+    buildah podman skopeo runc crun qemu-user-binfmt jq curl fuse-overlayfs nftables netavark
   # - sed -i '/^mountopt =.*/d' /etc/containers/storage.conf
   # Not sure why it won't take options from /etc/containers/containers.conf
   - |
@@ -58,7 +58,11 @@ before_script:
     ##EOF
     #sed -i -E -e 's|#mount_program = "/usr/bin/fuse-overlayfs"|mount_program = "/usr/bin/fuse-overlayfs"|' /etc/containers/storage.conf
 
-  - podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes
+  - |
+    podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes
+    if [[ $? -ne 0 ]]; then
+      echo "Warning: qemu-user-static setup failed, but continuing anyway."
+    fi
   - buildah login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
   # Cosign currently relies on Docker to operate
   - |
